### ISSUE TITLE
Is the "transformative reaction" formula wrong?

### ISSUE THREAD

**Issue by SuperCuber** [KQM-git/TCL#198]
I think instead of `(1 + EM_FRACTION + ReactionBonus)` it should be `ReactionBonus x (1+ EM_FRACTION)` - this change is consistent with the output of the [calculator](genshin.aspirine.su) i used as well as in game testing. And makes more sense considering the table in "hyperbloom" section of this [wiki page](https://genshin-impact.fandom.com/wiki/Bloom) features a pre-multiplied by 3 value of the level multiplier

**Comment by SuperCuber** [comment]
On second reading, i see there's "reaction multiplier" which is where i should've plugged in the `3` for hyperbloom... But then it's unclear what is the "ReactionBonus" - it's not mentioned anywhere else, does this mean "elemental damage bonus %", so for example `0.15` for dendro set? If so it's kinda unclear. And also, could you mention which elemental bonuses does each reaction benefit from? I can't find this information anywhere. :)

**Comment by sharaths21312** [comment]
The bonus is for any effect that gives reaction damage, for example the 4pc flower of paradise lost or thundering fury sets. Elemental damage bonus (like on 2pc deepwood) does not affect transformative reaction damage at all.

Also for feedback/queries regarding the info in the TCL you should ask in the [discord](https://discord.gg/keqing) instead of here.
